name: Generate Snake Game

on:
  schedule:
    - cron: "0 0 * * *"  # Atualiza todo dia à meia-noite
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: PeterSteve234
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Push Snake
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
