name: Generate Snake Animation

on:
  schedule:
    # Roda a cada 12 horas (pode ajustar, mas este é um bom padrão)
    - cron: "0 */12 * * *" 
  workflow_dispatch:

jobs:
  generate:
    permissions:
      contents: write # Permissão necessária para a Action salvar o arquivo SVG
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Generate github-contribution-grid-snake.svg
        uses: Platane/snk@v3
        with:
          # Usa o nome do dono do repositório, não precisa mudar!
          github_user_name: ${{ github.repository_owner }} 
          # Lista de arquivos a serem gerados: SVG padrão e um para Dark Mode
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push the SVG to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
